name: nodejs
on: push
jobs:
   jobname:
   	runs-on: ubuntu-latest
 	steps:
 	  - name: Get code
 	    uses: actions/checkout@3   #to get code from repository. This is an action.
	  - name: Install Node.JS
	    uses: actions/setup-node@v3
 	    with:                                       #configuration details 
	      node-version:  18
    - name: Install dependencies
 	    run: npm ci
    - name: Run tests
      run: npm test

  
